### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Pyth3rEx**

### CODE REVIEW

**Comment by MaDHouSe79** [comment]
a i see the dot, thanks for notice 😄

**Comment by Pyth3rEx** [comment]
Thanks for all your cool scripts man ;)
They are bugged quite a bit and could use a makeover but having so much free opensource ressources is awsome!
Let me know if you want to work together on something someday! (you can add me on discord ;) )

**Comment by MaDHouSe79** [comment]
i am busy with state bags to see how that works, i want to use that for the trailer script i have it for the carlift but now i want te see if i can create this for the trailer script aswell, so it is synced with all players. 😅

**Comment by Pyth3rEx** [comment]
sounds cool! looking forward to see what you can come up with!

**Comment by MaDHouSe79** [comment]
I've been working on it for almost half an hour maby 15 min to day and I have the server side almost ready 😄

**Comment by Pyth3rEx** [comment]
What's your discord?

**Comment by MaDHouSe79** [comment]
i don't use discord anymore, i just deleted my server, cause no one was using it, and that for almost 400 people, so i deleted it.

**Comment by Pyth3rEx** [comment]
that's a shame :/

**Comment by MaDHouSe79** [comment]
Oh what the heck it doesn't matter to me, people come for help and then you helped them and fix the issue and then they leave without saying anything, and of course there are people who appreciate it, but very few.

**Pull request closed without merging**
